#!/usr/bin/env ruby

# run as:
#   ltg match killa dummy 2>&1 | grep "=\|Exception" | grep -v Sys_error | head -n 30
#
# 2>&1 because ltg send to stderr
# grep for = and Exception to see slots and any errors
# grep agains Sys_error 'cause I get pipe errors, bullshit
# head 30 in case you got an infinite loop...



require './lib/dsl'
# DSL docs:
# all commands use small letters
#
# To apply as function (code 2) add ! at the end
#
# default slot is 0, pass an integer to use another
#
# Eg. (inf loop example) s ; get ; i ; zero

#slot 0 do
#    s; inc; i # set up inner code
#
#    slot(1) { s; get; pp :get, :zero }
#
#    put! # clear slot 0
#    get; pp :succ, :zero
#    zero # execute
#end

def recurse_attack()
    slot 0 do
        zero; succ!;
        dbl!; dbl!; dbl!; dbl!; dbl!; dbl!; dbl!; dbl!;
        dbl!; dbl!; dbl!; dbl!; #dbl!; dbl!; dbl!; dbl!;
    end

    slot 1 do
        attack; zero; pp :succ, :zero; pp :get, :zero
    end
end

def recurse_dec()
    slot 0 do
        slot(1) { s; dec; i } 
        s; get; pp :get, :succ, :zero; zero
    end
end

recurse_dec
slot(0) { put! }
slot(1) { put! }
recurse_attack
